create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null,
  description text not null,
  outcome text,
  tech_stack text[] default '{}',
  image_url text,
  live_url text,
  repo_url text,
  featured boolean default false,
  published boolean default false,
  sort_order integer default 0,
  created_at timestamptz default now()
);

create table if not exists public.skills (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  sort_order integer default 0
);

create table if not exists public.experience (
  id bigint generated by default as identity primary key,
  role text not null,
  company text not null,
  date_range text not null,
  description text not null,
  sort_order integer default 0
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  message text not null,
  is_read boolean default false,
  created_at timestamptz default now()
);

alter table public.projects enable row level security;
alter table public.skills enable row level security;
alter table public.experience enable row level security;
alter table public.messages enable row level security;

create policy "Published projects are public" on public.projects for select using (published = true);
create policy "Skills are public" on public.skills for select using (true);
create policy "Experience is public" on public.experience for select using (true);
create policy "Anyone can send a message" on public.messages for insert with check (true);
create policy "Owner manages projects" on public.projects for all to authenticated using (true) with check (true);
create policy "Owner manages skills" on public.skills for all to authenticated using (true) with check (true);
create policy "Owner manages experience" on public.experience for all to authenticated using (true) with check (true);
create policy "Owner manages messages" on public.messages for all to authenticated using (true) with check (true);
