import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { createClient } from '@supabase/supabase-js';
import { AnimatePresence, motion } from 'framer-motion';
import { FiActivity, FiArrowUpRight, FiBriefcase, FiCheckCircle, FiChevronRight, FiClock, FiCode, FiEdit3, FiEye, FiGithub, FiLayout, FiLinkedin, FiLogOut, FiMail, FiMenu, FiMessageSquare, FiMoon, FiPlus, FiSettings, FiSun, FiTrash2, FiX } from 'react-icons/fi';
import './styles.css';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseKey = import.meta.env.VITE_SUPABASE_ANON_KEY;
const supabase = supabaseUrl && supabaseKey ? createClient(supabaseUrl, supabaseKey) : null;
const navItems = ['Home', 'About', 'Process', 'Skills', 'Portfolio', 'Services', 'Contact'];
const projects = [
  { title: 'Nova Finance', category: 'Fintech dashboard', description: 'A focused financial workspace that turns complex numbers into confident decisions.', tags: ['React', 'Product UI', 'Supabase'], tone: 'blue', featured: true },
  { title: 'Form Studio', category: 'Creative platform', description: 'A flexible digital home for a design practice with a strong visual point of view.', tags: ['React', 'Design system', 'CMS'], tone: 'gold', featured: true },
  { title: 'Field Notes', category: 'Editorial platform', description: 'A publishing experience designed around calm reading and simple content operations.', tags: ['Next.js', 'Content', 'API'], tone: 'violet' },
  { title: 'Ops Board', category: 'Internal tool concept', description: 'A clearer way for teams to see work, ownership, and the next useful action.', tags: ['TypeScript', 'Workflow', 'UX'], tone: 'green' },
  { title: 'Market Home', category: 'Commerce concept', description: 'A fast storefront foundation that gives products room to be understood.', tags: ['Frontend', 'Commerce', 'Responsive'], tone: 'rose' },
];
const skills = ['React', 'JavaScript', 'TypeScript', 'Node.js', 'Supabase', 'PostgreSQL', 'REST APIs', 'Responsive UI', 'Design systems', 'Accessibility', 'Git', 'Vercel'];
const process = [['01', 'Understand', 'Start with the people, constraints, and outcome behind the brief.'], ['02', 'Shape', 'Turn the messy middle into a clear product direction and visual system.'], ['03', 'Ship', 'Build, test, and refine until the work feels simple to use and ready for real life.']];
const reveal = { hidden: { opacity: 0, y: 24 }, show: { opacity: 1, y: 0, transition: { duration: .6, ease: [.22, 1, .36, 1] } } };
const stagger = { hidden: {}, show: { transition: { staggerChildren: .09 } } };
function Arrow() { return <FiArrowUpRight className="arrow-icon" aria-hidden="true" />; }

function PublicSite() {
  const [theme, setTheme] = useState(() => localStorage.getItem('kalab-theme') || 'dark'); const [menuOpen, setMenuOpen] = useState(false); const [contact, setContact] = useState({ name: '', email: '', message: '' }); const [contactState, setContactState] = useState('idle');
  useEffect(() => { document.documentElement.dataset.theme = theme; localStorage.setItem('kalab-theme', theme); }, [theme]);
  const submitContact = async (event) => { event.preventDefault(); setContactState('sending'); if (supabase) { const { error } = await supabase.from('messages').insert(contact); if (error) { setContactState('error'); return; } } setContactState('sent'); setContact({ name: '', email: '', message: '' }); };
  return <div className="reference-site"><header className="reference-nav"><a className="reference-brand" href="#home"><span>KA</span><strong>Kalab</strong></a><nav className={menuOpen ? 'reference-links open' : 'reference-links'}>{navItems.map((item) => <a key={item} href={`#${item.toLowerCase()}`} onClick={() => setMenuOpen(false)}>{item}</a>)}</nav><div className="nav-actions"><button className="theme-toggle" onClick={() => setTheme(theme === 'dark' ? 'light' : 'dark')} aria-label="Toggle color theme">{theme === 'dark' ? <FiSun /> : <FiMoon />}</button><a className="nav-contact" href="#contact">Contact <Arrow /></a><button className="mobile-toggle" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle menu">{menuOpen ? <FiX /> : <FiMenu />}</button></div></header><main>
    <motion.section id="home" className="reference-hero" initial="hidden" animate="show" variants={stagger}><div className="hero-glow glow-one" /><div className="hero-glow glow-two" /><div className="grid-overlay" /><motion.div className="hero-content" variants={reveal}><div className="status-pill"><span /> Available for opportunities</div><h1>Building digital products with <span>clarity.</span></h1><p className="hero-role">Frontend-first / Full-stack developer</p><p className="hero-copy">I’m Kalab Awoke, a developer based in Addis Ababa building production-minded web experiences across product, commerce, and internal tools.</p><div className="hero-buttons"><a className="primary-button" href="#portfolio">View my work <Arrow /></a><a className="secondary-button" href="#contact">Let’s connect <Arrow /></a></div><div className="social-row"><a href="https://github.com/kal400" target="_blank" rel="noreferrer"><FiGithub /> GitHub</a><a href="https://www.linkedin.com" target="_blank" rel="noreferrer"><FiLinkedin /> LinkedIn</a><a href="mailto:kaleabawoe@gmail.com"><FiMail /> Email</a></div></motion.div><motion.div className="hero-photo" variants={reveal}><img src="/photo.jpg" alt="Kalab Awoke illustrated portrait" /><span>PROFILE / 01</span></motion.div><div className="hero-orbit orbit-a" /><div className="hero-orbit orbit-b" /><div className="hero-mark">KA<span>01</span></div></motion.section>
    <motion.section className="stats-strip" initial="hidden" whileInView="show" viewport={{ once: true, amount: .4 }} variants={stagger}>{[['3+', 'Ways I build'], ['12', 'Core tools'], ['∞', 'Curiosity']].map(([value, label]) => <motion.div variants={reveal} key={label}><strong>{value}</strong><span>{label}</span></motion.div>)}<p>From the first sketch<br />to the last detail.</p></motion.section>
    <Section id="about" number="01" title="About me"><div className="about-grid"><motion.div variants={reveal}><h2>Full-stack thinking, <em>frontend-first</em> craft.</h2></motion.div><motion.div className="about-copy" variants={reveal}><p>I care about making digital products feel obvious in the best way. That means clear decisions, thoughtful interfaces, and code that stays understandable after launch.</p><p>My work sits between product thinking, visual systems, and implementation. I’m comfortable moving from an open question to a responsive interface, a working data flow, and the details that make a product feel trustworthy.</p><a className="inline-link" href="#contact">More about my approach <Arrow /></a></motion.div></div></Section>
    <Section id="process" number="02" title="How I work" className="process-section"><h2 className="section-title">A useful process for <em>real work.</em></h2><motion.div className="process-grid" variants={stagger} initial="hidden" whileInView="show" viewport={{ once: true, amount: .3 }}>{process.map(([number, title, copy]) => <motion.article variants={reveal} key={number}><span className="process-number">{number}</span><h3>{title}</h3><p>{copy}</p><span className="process-line" /></motion.article>)}</motion.div></Section>
    <Section id="skills" number="03" title="Skills & tools"><div className="skills-layout"><h2>Tools for making<br /><em>useful things.</em></h2><motion.div className="skill-pills" variants={stagger} initial="hidden" whileInView="show" viewport={{ once: true, amount: .3 }}>{skills.map((skill) => <motion.span variants={reveal} key={skill}>{skill}</motion.span>)}</motion.div></div></Section>
    <Section id="portfolio" number="04" title="Selected work" className="portfolio-section"><div className="portfolio-heading"><h2>Projects I’ve <em>shaped.</em></h2><p>Concepts and shipped work across interfaces, systems, and the messy middle where products become useful.</p></div><motion.div className="portfolio-grid" variants={stagger} initial="hidden" whileInView="show" viewport={{ once: true, amount: .2 }}>{projects.map((project, index) => <motion.article variants={reveal} whileHover={{ y: -6 }} className="portfolio-card" key={project.title}><div className={`project-image tone-${project.tone}`}><span className="project-index">0{index + 1}</span><span className="project-symbol">{project.title.slice(0, 1)}</span><span className="project-category">{project.category}</span></div><div className="project-details"><div><h3>{project.title}</h3><p>{project.description}</p><div className="tag-row">{project.tags.map((tag) => <span key={tag}>{tag}</span>)}</div></div><Arrow /></div></motion.article>)}</motion.div></Section>
    <Section id="services" number="05" title="What I build"><div className="service-list">{[['01', 'Product interfaces', 'Responsive frontend systems that make complicated workflows feel calm and clear.'], ['02', 'Full-stack foundations', 'Auth, data flows, APIs, dashboards, and the dependable parts behind the interface.'], ['03', 'Design-minded development', 'A strong visual point of view carried through spacing, states, motion, and accessibility.']].map(([num, title, copy]) => <motion.article whileHover={{ x: 8 }} key={num}><span>{num}</span><div><h3>{title}</h3><p>{copy}</p></div><Arrow /></motion.article>)}</div></Section>
    <section id="contact" className="contact-section"><div className="contact-inner"><div className="section-kicker"><span>06</span><b>Contact</b></div><h2>Have a good idea?<br /><em>Let’s make it real.</em></h2><div className="contact-grid"><div><p>Open to thoughtful collaborations, product teams, and opportunities where good work has room to matter.</p><a className="contact-email" href="mailto:kaleabawoe@gmail.com">kaleabawoe@gmail.com <Arrow /></a></div><form onSubmit={submitContact}><label>Name<input required value={contact.name} onChange={(e) => setContact({ ...contact, name: e.target.value })} /></label><label>Email<input required type="email" value={contact.email} onChange={(e) => setContact({ ...contact, email: e.target.value })} /></label><label>Message<textarea required rows="4" value={contact.message} onChange={(e) => setContact({ ...contact, message: e.target.value })} /></label><button className="primary-button" disabled={contactState === 'sending'}>{contactState === 'sending' ? 'Sending…' : contactState === 'sent' ? 'Message sent ✓' : 'Send message'} <Arrow /></button>{contactState === 'error' && <small>Could not send. Please email me directly.</small>}</form></div></div></section></main><footer className="reference-footer"><span>© 2026 Kalab Awoke</span><span>Built with care in Addis Ababa</span><a href="#home">Back to top ↑</a></footer></div>;
}

function Section({ id, number, title, className = '', children }) { return <motion.section id={id} className={`content-section ${className}`} initial="hidden" whileInView="show" viewport={{ once: true, amount: .12 }} variants={stagger}><div className="section-kicker"><span>{number}</span><b>{title}</b></div>{children}</motion.section>; }

const adminNav = [{ label: 'Overview', icon: FiActivity }, { label: 'Projects', icon: FiBriefcase }, { label: 'Skills', icon: FiCode }, { label: 'Experience', icon: FiLayout }, { label: 'Messages', icon: FiMessageSquare }];
function AdminLogin({ onLogin }) { const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const login = async (event) => { event.preventDefault(); setError(''); if (!supabase) { onLogin({ email: email || 'demo@local.dev' }); return; } const { data, error: authError } = await supabase.auth.signInWithPassword({ email, password }); if (authError) setError(authError.message); else onLogin(data.user); }; return <motion.div className="admin-shell auth-shell" initial={{ opacity: 0 }} animate={{ opacity: 1 }}><motion.div className="auth-card" initial={{ y: 25, opacity: 0 }} animate={{ y: 0, opacity: 1 }} transition={{ delay: .1 }}><a className="reference-brand" href="#home"><span>KA</span><strong>Kalab</strong></a><p className="eyebrow">Private workspace</p><h1>Welcome back.</h1><p>Manage the work, skills, experience, and messages shown on your portfolio.</p><form onSubmit={login}><label>Email<input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} /></label><label>Password<input required type="password" value={password} onChange={(e) => setPassword(e.target.value)} /></label><button className="primary-button">Sign in <Arrow /></button>{error && <small>{error}</small>}{!supabase && <small>Demo mode: connect Supabase variables for real authentication.</small>}</form></motion.div></motion.div>; }

function AdminDashboard({ user, onLogout }) { const [active, setActive] = useState('Overview'); const [sidebarOpen, setSidebarOpen] = useState(false); const [showNew, setShowNew] = useState(false); const [projectList, setProjectList] = useState(projects); const unread = 2; const stats = [{ label: 'Published projects', value: projectList.length, icon: FiBriefcase, trend: '+2 this month' }, { label: 'Skills listed', value: skills.length, icon: FiCode, trend: '4 categories' }, { label: 'Unread messages', value: unread, icon: FiMessageSquare, trend: 'Needs attention' }]; return <motion.div className="admin-shell" initial={{ opacity: 0 }} animate={{ opacity: 1 }}><aside className={sidebarOpen ? 'admin-sidebar is-open' : 'admin-sidebar'}><div className="admin-brand-row"><a className="reference-brand" href="#home"><span>KA</span><strong>Admin</strong></a><button className="mobile-toggle" onClick={() => setSidebarOpen(false)}><FiX /></button></div><nav>{adminNav.map(({ label, icon: Icon }) => <button className={active === label ? 'active' : ''} onClick={() => { setActive(label); setSidebarOpen(false); }} key={label}><Icon />{label}{label === 'Messages' && <b>{unread}</b>}</button>)}</nav><div className="admin-sidebar-bottom"><span><FiSettings /> Settings</span><button className="logout" onClick={onLogout}><FiLogOut /> Log out</button></div></aside><main className="admin-main"><div className="admin-topbar"><button className="admin-menu-button" onClick={() => setSidebarOpen(true)}><FiMenu /></button><div><p className="eyebrow">Portfolio workspace</p><h1>{active}</h1></div><div className="admin-user"><span className="admin-avatar">{(user.email || 'K').slice(0, 1).toUpperCase()}</span><span>{user.email}</span></div></div><AnimatePresence mode="wait"><motion.div key={active} initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }} transition={{ duration: .25 }}>{active === 'Overview' ? <AdminOverview stats={stats} onNew={() => setShowNew(true)} setActive={setActive} /> : <AdminCollection title={active} rows={active === 'Projects' ? projectList : active === 'Skills' ? skills : active === 'Experience' ? ['Independent developer', 'Product-focused builder'] : ['Your next project starts here', 'Collaboration opportunity']} onNew={active === 'Projects' ? () => setShowNew(true) : undefined} />}</motion.div></AnimatePresence>{showNew && <NewProjectModal onClose={() => setShowNew(false)} onSave={(project) => { setProjectList([project, ...projectList]); setShowNew(false); }} />}</main></motion.div>; }
function AdminOverview({ stats, onNew, setActive }) { return <><div className="admin-welcome"><div><span className="eyebrow">Good morning, Kalab</span><h2>Your portfolio at a glance.</h2><p>Keep your work fresh and your story moving forward.</p></div><button className="primary-button" onClick={onNew}><FiPlus /> New project</button></div><div className="admin-stats">{stats.map(({ label, value, icon: Icon, trend }) => <motion.div className="admin-stat" whileHover={{ y: -4 }} key={label}><div className="stat-icon"><Icon /></div><span>{label}</span><strong>{value}</strong><small><FiCheckCircle /> {trend}</small></motion.div>)}</div><div className="admin-grid-panels"><section className="admin-panel"><div className="panel-header"><div><p className="eyebrow">Recently updated</p><h2>Work library</h2></div><button onClick={() => setActive('Projects')}>View all <FiChevronRight /></button></div>{projects.slice(0, 3).map((project, i) => <div className="admin-list-row" key={project.title}><span className={`mini-project tone-${project.tone}`}>{String(i + 1).padStart(2, '0')}</span><div><strong>{project.title}</strong><small>{project.category}</small></div><span className="status-badge"><FiEye /> Published</span><FiEdit3 className="row-action" /></div>)}</section><section className="admin-panel activity-panel"><div className="panel-header"><div><p className="eyebrow">Inbox</p><h2>Messages</h2></div><button onClick={() => setActive('Messages')}>Open inbox <FiChevronRight /></button></div><div className="message-preview"><span className="message-dot" /><div><strong>Your next project starts here</strong><small>New message · Today</small></div><FiChevronRight /></div><div className="message-preview muted"><FiClock /><div><strong>Collaboration opportunity</strong><small>Read · Yesterday</small></div></div></section></div></>; }
function AdminCollection({ title, rows, onNew }) { return <section className="admin-panel collection-panel"><div className="panel-header"><div><p className="eyebrow">Manage content</p><h2>{title}</h2></div>{onNew && <button className="primary-button" onClick={onNew}><FiPlus /> Add project</button>}</div><div className="collection-toolbar"><span>{rows.length} records</span><button><FiActivity /> Recently updated</button></div>{rows.map((row, index) => { const label = typeof row === 'string' ? row : row.title; return <motion.div className="admin-list-row" whileHover={{ x: 4 }} key={label}><span className="row-number">{String(index + 1).padStart(2, '0')}</span><div><strong>{label}</strong><small>{typeof row === 'string' ? title.slice(0, -1) : row.category}</small></div><span className="status-badge"><FiCheckCircle /> Published</span><button className="icon-action"><FiEdit3 /></button><button className="icon-action danger"><FiTrash2 /></button></motion.div>; })}</section>; }
function NewProjectModal({ onClose, onSave }) { const [title, setTitle] = useState(''); const [category, setCategory] = useState(''); return <div className="modal-backdrop" onClick={onClose}><motion.div className="project-modal" initial={{ opacity: 0, y: 20, scale: .97 }} animate={{ opacity: 1, y: 0, scale: 1 }} onClick={(event) => event.stopPropagation()}><div className="panel-header"><div><p className="eyebrow">Projects</p><h2>Add a project</h2></div><button className="icon-action" onClick={onClose}><FiX /></button></div><form onSubmit={(e) => { e.preventDefault(); onSave({ title: title || 'Untitled project', category: category || 'New project', description: 'Add a project description from the dashboard.', tags: ['New'], tone: 'blue' }); }}><label>Project title<input autoFocus value={title} onChange={(e) => setTitle(e.target.value)} placeholder="e.g. Client dashboard" /></label><label>Category<input value={category} onChange={(e) => setCategory(e.target.value)} placeholder="e.g. Product design" /></label><div className="modal-actions"><button type="button" className="secondary-button" onClick={onClose}>Cancel</button><button className="primary-button"><FiPlus /> Create project</button></div></form></motion.div></div>; }
function App() { const [admin, setAdmin] = useState(window.location.hash.startsWith('#admin')); const [user, setUser] = useState(null); useEffect(() => { const onHash = () => setAdmin(window.location.hash.startsWith('#admin')); window.addEventListener('hashchange', onHash); return () => window.removeEventListener('hashchange', onHash); }, []); if (!admin) return <PublicSite />; return user ? <AdminDashboard user={user} onLogout={() => setUser(null)} /> : <AdminLogin onLogin={setUser} />; }
createRoot(document.getElementById('root')).render(<React.StrictMode><App /></React.StrictMode>);
