import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { createClient } from '@supabase/supabase-js';
import './styles.css';

const projects = [
  { title: 'Nova Finance', type: 'Product / Frontend', description: 'A calmer way to understand personal finance through clear dashboards and purposeful interactions.', result: 'Product thinking · React · Responsive UI', color: 'lime', featured: true },
  { title: 'Form Studio', type: 'Brand / Digital', description: 'A confident digital home for a small creative practice with a flexible visual system.', result: 'Art direction · Design systems · Web', color: 'orange' },
  { title: 'Field Notes', type: 'Editorial / Full-stack', description: 'An editorial platform that makes thoughtful publishing feel simple and human.', result: 'Content systems · APIs · Development', color: 'blue' },
];
const skills = { Frontend: ['HTML & CSS', 'JavaScript', 'React', 'Responsive UI'], Backend: ['Node.js', 'REST APIs', 'Supabase', 'Git'], Design: ['Design systems', 'Wireframing', 'Prototyping', 'Accessibility'], Tools: ['Figma', 'Vite', 'GitHub', 'Vercel'] };
const experience = [
  { date: 'Now', role: 'Independent developer', company: 'Building useful digital products', text: 'Working across interface design, frontend engineering, and product thinking.' },
  { date: '2024 — 2025', role: 'Product-focused builder', company: 'Selected digital projects', text: 'Turning early ideas into clear, responsive, and maintainable web experiences.' },
];
const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseKey = import.meta.env.VITE_SUPABASE_ANON_KEY;
const supabase = supabaseUrl && supabaseKey ? createClient(supabaseUrl, supabaseKey) : null;
function Icon({ children }) { return <span className="icon" aria-hidden="true">{children}</span>; }

function PublicSite() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [contact, setContact] = useState({ name: '', email: '', message: '' });
  const [contactState, setContactState] = useState('idle');
  const submitContact = async (event) => { event.preventDefault(); setContactState('sending'); if (supabase) { const { error } = await supabase.from('messages').insert(contact); if (error) { setContactState('error'); return; } } setContactState('sent'); setContact({ name: '', email: '', message: '' }); };
  const closeMenu = () => setMenuOpen(false);
  return <div className="site-shell">
    <header className="site-header"><a className="brand" href="#top"><span>KA</span><strong>Kalab Awoke</strong></a><button className="menu-toggle" onClick={() => setMenuOpen(!menuOpen)} aria-expanded={menuOpen}>Menu <span>{menuOpen ? '−' : '+'}</span></button><nav className={menuOpen ? 'site-nav is-open' : 'site-nav'} aria-label="Main navigation"><a href="#work" onClick={closeMenu}>Work</a><a href="#skills" onClick={closeMenu}>Skills</a><a href="#about" onClick={closeMenu}>About</a><a href="#contact" onClick={closeMenu}>Contact</a></nav><a className="header-cta" href="mailto:kaleabawoe@gmail.com">Let’s talk <Icon>↗</Icon></a></header>
    <main id="top">
      <section className="hero section-wrap"><div className="hero-copy"><p className="eyebrow"><span className="status-dot" /> Available for opportunities · Addis Ababa</p><h1>Building digital products with <em>clarity</em> and character.</h1><p className="hero-intro">I’m Kalab, a frontend and full-stack developer with a designer’s eye for useful, memorable experiences.</p><div className="hero-actions"><a className="button button-dark" href="#work">View my work <Icon>↓</Icon></a><a className="text-link" href="#contact">Let’s connect <Icon>↗</Icon></a></div></div><div className="portrait-wrap" aria-label="Portrait placeholder for Kalab Awoke"><div className="portrait-accent" /><div className="portrait-card"><img src="/avatar-placeholder.svg" alt="Replaceable professional portrait placeholder" /><span className="portrait-label">PORTRAIT / 01</span></div><span className="portrait-note">A developer who cares about the details people feel.</span></div></section>
      <section className="marquee" aria-label="Capabilities"><div>Frontend <span>✳</span> Full-stack <span>✳</span> UI / UX <span>✳</span> Frontend <span>✳</span> Full-stack <span>✳</span> UI / UX <span>✳</span></div></section>
      <section id="work" className="section-wrap section-block"><div className="section-heading"><p className="eyebrow">01 — Selected work</p><p className="section-note">Editable project content will live in the admin dashboard.</p></div><div className="project-grid">{projects.map((project) => <article className={project.featured ? 'project-card project-featured' : 'project-card'} key={project.title}><div className={`project-visual visual-${project.color}`}><span className="visual-word">{project.title.split(' ')[0].toUpperCase()}</span><span className="visual-chip">{project.type}</span><span className="visual-grid" /></div><div className="project-meta"><div><h2>{project.title}</h2><p>{project.description}</p><small>{project.result}</small></div><span className="arrow"><Icon>↗</Icon></span></div></article>)}</div></section>
      <section id="skills" className="section-wrap section-block skills-section"><div className="section-heading"><p className="eyebrow">02 — What I bring</p><p className="section-note">A practical mix of making and thinking.</p></div><div className="skills-grid">{Object.entries(skills).map(([group, items]) => <div className="skill-group" key={group}><p className="eyebrow">{group}</p>{items.map((item) => <span key={item}>{item}</span>)}</div>)}</div></section>
      <section id="experience" className="section-wrap section-block experience-section"><div className="section-heading"><p className="eyebrow">03 — Experience</p><p className="section-note">Growing through real projects and useful outcomes.</p></div><div className="experience-list">{experience.map((item) => <article className="experience-row" key={item.role}><span className="experience-date">{item.date}</span><div><h3>{item.role}</h3><p className="experience-company">{item.company}</p><p>{item.text}</p></div></article>)}</div></section>
      <section id="about" className="section-wrap split-section"><div><p className="eyebrow">04 — A little about me</p></div><div className="large-copy"><h2>Good work sits at the intersection of <em>thinking</em> and making.</h2><p>I enjoy taking messy ideas and giving them a clear shape. My process is collaborative, practical, and grounded in the details that help people move through a product with confidence.</p><a className="text-link" href="mailto:kaleabawoe@gmail.com">Start a conversation <Icon>↗</Icon></a></div></section>
      <section id="contact" className="contact-section"><div className="section-wrap contact-inner"><p className="eyebrow">05 — Start a conversation</p><h2>Have a good idea?<br /><em>Let’s make it real.</em></h2><div className="contact-layout"><div><a className="contact-email" href="mailto:kaleabawoe@gmail.com">kaleabawoe@gmail.com <Icon>↗</Icon></a><div className="contact-links"><a href="https://github.com/kal400" target="_blank" rel="noreferrer">GitHub</a><a href="https://www.linkedin.com" target="_blank" rel="noreferrer">LinkedIn</a><a href="#top">Back to top ↑</a></div></div><form className="contact-form" onSubmit={submitContact}><label>Your name<input required value={contact.name} onChange={(e) => setContact({ ...contact, name: e.target.value })} /></label><label>Your email<input required type="email" value={contact.email} onChange={(e) => setContact({ ...contact, email: e.target.value })} /></label><label>Message<textarea required rows="4" value={contact.message} onChange={(e) => setContact({ ...contact, message: e.target.value })} /></label><button className="button button-lime" disabled={contactState === 'sending'}>{contactState === 'sending' ? 'Sending…' : contactState === 'sent' ? 'Message sent ✓' : 'Send message ↗'}</button>{contactState === 'error' && <p className="form-note">Something went wrong. Please email me directly.</p>}</form></div></div></section>
    </main><footer className="site-footer"><span>© 2026 Kalab Awoke</span><span>Designed & built with intent.</span></footer>
  </div>;
}

function AdminLogin({ onLogin }) {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState('');
  const login = async (event) => { event.preventDefault(); setError(''); if (!supabase) { onLogin({ email: email || 'demo@local.dev' }); return; } const { data, error: authError } = await supabase.auth.signInWithPassword({ email, password }); if (authError) setError(authError.message); else onLogin(data.user); };
  return <div className="admin-shell auth-shell"><div className="auth-card"><a className="brand" href="#top"><span>KA</span><strong>Kalab Awoke</strong></a><p className="eyebrow">Private workspace</p><h1>Welcome back.</h1><p>Sign in to manage the work, skills, experience, and messages shown on your portfolio.</p><form onSubmit={login}><label>Email<input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="you@example.com" /></label><label>Password<input required type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="••••••••" /></label><button className="button button-dark">Sign in <Icon>↗</Icon></button>{error && <p className="form-note error">{error}</p>}{!supabase && <p className="form-note">Demo mode: connect Supabase environment variables for real authentication.</p>}</form></div></div>;
}

function AdminDashboard({ user, onLogout }) { const [active, setActive] = useState('Overview'); const nav = ['Overview', 'Projects', 'Skills', 'Experience', 'Messages']; return <div className="admin-shell"><aside className="admin-sidebar"><a className="brand" href="#top"><span>KA</span><strong>Admin</strong></a><nav>{nav.map((item) => <button className={active === item ? 'active' : ''} onClick={() => setActive(item)} key={item}>{item}</button>)}</nav><button className="logout" onClick={onLogout}>Log out ↗</button></aside><main className="admin-main"><div className="admin-topbar"><div><p className="eyebrow">Portfolio workspace</p><h1>{active}</h1></div><span className="admin-user">{user.email}</span></div>{active === 'Overview' && <><div className="overview-grid"><div><span>Published projects</span><strong>03</strong></div><div><span>Skills listed</span><strong>16</strong></div><div><span>Unread messages</span><strong>02</strong></div></div><section className="admin-panel"><div className="panel-heading"><div><p className="eyebrow">Quick start</p><h2>Keep your story current.</h2></div><span className="panel-mark">✦</span></div><p>Use this workspace to update the public portfolio without touching the code. Connect Supabase to persist your changes.</p><button className="button button-dark" onClick={() => setActive('Projects')}>Manage projects <Icon>↗</Icon></button></section></>}{active !== 'Overview' && <ContentPanel title={active} />}</main></div>; }
function ContentPanel({ title }) { const rows = title === 'Messages' ? [{ title: 'Your next project starts here', meta: 'New · Today' }, { title: 'Collaboration opportunity', meta: 'Read · Yesterday' }] : title === 'Projects' ? projects.map((p) => ({ title: p.title, meta: p.featured ? 'Published · Featured' : 'Draft · Edit details' })) : title === 'Skills' ? Object.values(skills).flat().map((s) => ({ title: s, meta: 'Skill · Published' })) : experience.map((e) => ({ title: e.role, meta: e.date })); return <section className="admin-panel table-panel"><div className="panel-heading"><div><p className="eyebrow">Manage content</p><h2>{title}</h2></div><button className="button button-dark">+ Add new</button></div><div className="admin-table">{rows.map((row) => <div className="admin-row" key={row.title}><strong>{row.title}</strong><span>{row.meta}</span><button aria-label={`Edit ${row.title}`}>Edit ↗</button></div>)}</div></section>; }
function App() { const [admin, setAdmin] = useState(window.location.hash.startsWith('#admin')); const [user, setUser] = useState(null); useEffect(() => { const handleHash = () => setAdmin(window.location.hash.startsWith('#admin')); window.addEventListener('hashchange', handleHash); return () => window.removeEventListener('hashchange', handleHash); }, []); if (!admin) return <PublicSite />; return user ? <AdminDashboard user={user} onLogout={() => setUser(null)} /> : <AdminLogin onLogin={setUser} />; }
createRoot(document.getElementById('root')).render(<React.StrictMode><App /></React.StrictMode>);
